Repository JetBrains/teamcity-docker-images, pull requests merged in 2025-01, with the labels that each got.

#179 TW-91535 Update Perforce Client within TeamCity Docker Images: 2022.2-2637361 -> 2022.2-2693782
  configs/linux.config
  context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
  context/generated/linux/Server/Ubuntu/18.04/Dockerfile
  context/generated/linux/Server/Ubuntu/20.04/Dockerfile
  context/generated/linux/Server/Ubuntu/22.04/Dockerfile
  context/generated/teamcity-agent.md
  context/generated/teamcity-server.md
Labels: dependencies, area/Dockerfiles

#178 Update dotnetcli domain
  configs/linux.config
  configs/linuxARM.config
  configs/windows.config
  context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/22.04/Dockerfile
  context/generated/teamcity-agent.md
  context/generated/windows/Agent/nanoserver/1803/Dockerfile
  context/generated/windows/Agent/windowsservercore/1803/Dockerfile
  context/generated/windows/Agent/windowsservercore/1809/Dockerfile
  context/generated/windows/Agent/windowsservercore/1903/Dockerfile
  context/generated/windows/Agent/windowsservercore/1909/Dockerfile
  context/generated/windows/Agent/windowsservercore/2022/Dockerfile
  custom/linux/agent/amd/custom.dotnet.sdk.amd.Dockerfile
  custom/linux/agent/arm/custom.dotnet.sdk.arm.Dockerfile
  custom/windows/agent/custom.dotnet.sdk.win.amd.Dockerfile
Labels: documentation, dependencies, area/Dockerfiles

#180 [TW] Replace package-based Git installation with multistage build from sources to keep Git 2.47.1
  configs/linux/Agent/Ubuntu/22.04/Ubuntu.Dockerfile.config
  configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
  configs/linux/Agent/UbuntuARM/22.04/UbuntuARM.Dockerfile.config
  configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerfile
  configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
  configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
  context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/22.04/Dockerfile
  context/generated/linux/Server/Ubuntu/18.04/Dockerfile
  context/generated/linux/Server/Ubuntu/20.04/Dockerfile
  context/generated/linux/Server/Ubuntu/22.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
Labels: dependencies, area/Dockerfiles

#182 [TW] Use multi-stage build for Git / Git LFS compilation for ARM Server images
  configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
  configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerfile
  configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
  context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/22.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
Labels: area/Dockerfiles

#183 [TW-91666] Docker Images: update Git LFS (3.0.2 -> 3.6.1)
  configs/linux.config
  configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
  configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerfile
  configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
  configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
  context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
  context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Agent/UbuntuARM/22.04/Dockerfile
  context/generated/linux/Server/Ubuntu/18.04/Dockerfile
  context/generated/linux/Server/Ubuntu/20.04/Dockerfile
  context/generated/linux/Server/Ubuntu/22.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
Labels: area/Dockerfiles

#184 [TW] Install 'software-properties-common' within ARM-based images
  configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
  configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
  context/generated/linux/Server/Ubuntu/18.04/Dockerfile
  context/generated/linux/Server/Ubuntu/20.04/Dockerfile
  context/generated/linux/Server/Ubuntu/22.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
Labels: area/Dockerfiles

#185 [TW-91776] Add the generation of the compiled locale data @ AMD images
  configs/linux/MinimalAgent/Ubuntu/Ubuntu.Dockerfile
  configs/linux/MinimalAgent/UbuntuARM/UbuntuARM.Dockerfile
  configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
  configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
  context/generated/linux/MinimalAgent/Ubuntu/18.04/Dockerfile
  context/generated/linux/MinimalAgent/Ubuntu/20.04/Dockerfile
  context/generated/linux/MinimalAgent/Ubuntu/22.04/Dockerfile
  context/generated/linux/MinimalAgent/UbuntuARM/18.04/Dockerfile
  context/generated/linux/MinimalAgent/UbuntuARM/20.04/Dockerfile
  context/generated/linux/MinimalAgent/UbuntuARM/22.04/Dockerfile
  context/generated/linux/Server/Ubuntu/18.04/Dockerfile
  context/generated/linux/Server/Ubuntu/20.04/Dockerfile
  context/generated/linux/Server/Ubuntu/22.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
  context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
Labels: area/Dockerfiles
